# Generated by Django 5.1.6 on 2025-02-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_created_at_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unfulfilled', 'Unfulfilled'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='unfulfilled'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Pending')], default='unpaid'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('waiting_for_pickup', 'Waiting For Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='waiting_for_pickup'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('esewa', 'Esewa'), ('paypal', 'Paypal'), ('card', 'Card')], default='cash'),
        ),
    ]
