# Generated by Django 5.1.6 on 2025-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_publisher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active'),
        ),
    ]
