// This is the root layout 
import type { Metadata } from "next"; // built-in import 1st
import { Poppins, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify"; // third-party import 2nd

import { ThemeProvider } from "@/providers/ThemeProvider"; // custom import 3rd 
import QueryProvider from "@/providers/QueryProvider";

import "./globals.css"; // css import last

// function comment 
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="default"
          >
            <ToastContainer />
            {children}
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html >
  );
}
